*&---------------------------------------------------------------------*
*& Include          ZFI_JV_EG_MASS_TOP
*&---------------------------------------------------------------------*
type-POOLs : slis.

DATA : LV_BUKRS TYPE BUKRS,
       LV_PARTN TYPE JV_PARTN,
       LV_VNAME TYPE JV_NAME,
       LV_ETYPE TYPE JV_ETYPE.

TYPES:
  BEGIN OF TY_T8JG,  "'1
    BUKRS TYPE T8JG-BUKRS,      "Company Code
    VNAME TYPE T8JG-VNAME,    "Joint venture
    ETYPE TYPE T8JG-ETYPE,   "Equity type
    FDATE TYPE T8JG-FDATE,      "Inverted Valid from Date
    EGRUP TYPE T8JG-EGRUP,  "Equity group
    VFROM TYPE D, " Valid From
    VTO   TYPE D,  " Valid To
  END OF TY_T8JG,

  BEGIN OF TY_T8J9A,
    BUKRS    TYPE BUKRS,
    JOA      TYPE JV_JOA,
    EGRUP    TYPE JV_AEGROUP,
    OPSHARE  TYPE JV_OPSHARE,
    NOPSHARE TYPE JV_NOSHARE,
  END OF TY_T8J9A,

  BEGIN OF TY_T8JVT,  "'2
    SPRAS TYPE SPRAS,
    BUKRS TYPE BUKRS,      "Company Code
    VNAME TYPE JV_NAME,    "JV Name
    VTEXT TYPE LTEXT_8JV,  "JV Description
  END OF TY_T8JVT,

  BEGIN OF TY_T8JFT,  "'3
    BUKRS TYPE BUKRS,
    VNAME TYPE JV_NAME,
    EGRUP TYPE T8JFT-EGRUP,
    EGTXT TYPE LTEXT_8JF,
  END OF TY_T8JFT.

*  TYPES:
**-- Single Value in Value Set
*       BEGIN OF zVRM_VALUE,
*         KEY(40) TYPE C,
*         TEXT(80) TYPE C,
*       END OF zVRM_VALUE.

DATA:
  IT_T8JG        TYPE STANDARD TABLE OF TY_T8JG,
  WA_T8JG        TYPE TY_T8JG,
  IT_T8JQ        TYPE STANDARD TABLE OF ZJVA_T8JQ,
  IT_ALLPARTNERS TYPE STANDARD TABLE OF ZJVA_T8JQ,
  WA_T8JQ        TYPE ZJVA_T8JQ,
  IT_T8JVT       TYPE STANDARD TABLE OF TY_T8JVT,
  WA_T8JVT       TYPE TY_T8JVT,
  IT_T8JFT       TYPE STANDARD TABLE OF TY_T8JFT,
  WA_T8JFT       TYPE TY_T8JFT,
  IT_T8J9A       TYPE STANDARD TABLE OF TY_T8J9A,
  IT_BUT000      TYPE STANDARD TABLE OF ZJVA_PARTNERNAMES,
  WA_BUT000      TYPE ZJVA_PARTNERNAMES,
  IT_PLIST       TYPE STANDARD TABLE OF ZJVA_SPLITTAB,
  WA_PLIST       TYPE ZJVA_SPLITTAB,
  IT_SLIST       TYPE ZJVA_NEWSPLITTYPE.

DATA: WA_SPLIT     TYPE ZJVA_SPLITTAB,
      IT_SPLIT     TYPE ZJVA_SPLITTABTYPE,
      WA_NPARTNERS TYPE ZJVA_SPLITSELTAB,
      IT_NPARTNERS TYPE ZJVA_SPLITSELTYPE.

DATA:IT_PFLDCAT TYPE  SLIS_T_FIELDCAT_ALV,
     WA_PFLDCAT TYPE  SLIS_FIELDCAT_ALV,
     WA_PLAYOUT TYPE  SLIS_LAYOUT_ALV,
     IT_SFLDCAT TYPE  SLIS_T_FIELDCAT_ALV,
     WA_SFLDCAT TYPE  SLIS_FIELDCAT_ALV,
     WA_SLAYOUT TYPE  SLIS_LAYOUT_ALV.

DATA: G_ETYPE      TYPE T8JE-ETYPE,
      G_VNAME      TYPE T8JV-VNAME,
      V_TOTALSPLIT TYPE I,
      V_DATE       TYPE CHAR8,
      V_TABIX      TYPE SY-TABIX.

FIELD-SYMBOLS: <FS_SLIST>  TYPE ZJVA_NEWSPLITTAB.

CONSTANTS: C_01(2)  TYPE C   VALUE '01'.

TYPES: BEGIN OF TY_NPARTNER,
         PARTNER TYPE T8JO-PARTN,
       END OF TY_NPARTNER.

DATA: WA_NPARTNER TYPE TY_NPARTNER,
      IT_NPARTNER TYPE STANDARD TABLE OF TY_NPARTNER.

DATA: V_CHG_ID TYPE ZCRA_RUNID.


DATA : it_stat TYPE vrm_values,
       w_line like LINE OF it_stat.
