*&---------------------------------------------------------------------*
*& Include          ZFI_JV_EG_MASS_SEL
*&---------------------------------------------------------------------*

SELECTION-SCREEN:BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
PARAMETERS: P_BUKRS TYPE T8JV-BUKRS   OBLIGATORY  ,
            P_PTROLD TYPE T8JO-PARTN  OBLIGATORY MATCHCODE OBJECT DEBI."  JV_PARTN
*            P_PTROLD TYPE T8JQ-PARTN OBLIGATORY.
PARAMETERS : P_SPLIT TYPE I OBLIGATORY.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(23) TEXT-002 FOR FIELD P_NPTR1.
PARAMETERS: P_NPTR1 TYPE T8JO-PARTN MATCHCODE OBJECT DEBI,
            P_SPLT1 TYPE I.
PARAMETERS : p_stat1 as LISTBOX VISIBLE LENGTH 8.
*SELECTION-SCREEN COMMENT 50(10) TEXT-S03.
SELECTION-SCREEN POSITION 60.
PARAMETERS : P_C1 AS CHECKBOX USER-COMMAND C1.
SELECTION-SCREEN COMMENT 65(5) TEXT-012 FOR FIELD P_C1.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(23) TEXT-003 FOR FIELD P_NPTR2 MODIF ID G2.
PARAMETERS: P_NPTR2 TYPE T8JO-PARTN MODIF ID G2 MATCHCODE OBJECT DEBI,
            P_SPLT2 TYPE I  MODIF ID G2.

PARAMETERS : p_stat2  as LISTBOX VISIBLE LENGTH 8 MODIF ID g2.

SELECTION-SCREEN POSITION 60.
PARAMETERS : P_C2 AS CHECKBOX MODIF ID G2 USER-COMMAND C1.
SELECTION-SCREEN COMMENT 65(5) TEXT-012 FOR FIELD P_C2 MODIF ID G2.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(23) TEXT-004 FOR FIELD P_NPTR3 MODIF ID G3.
PARAMETERS: P_NPTR3 TYPE T8JO-PARTN  MODIF ID G3 MATCHCODE OBJECT DEBI,
            P_SPLT3 TYPE I  MODIF ID G3.
PARAMETERS : p_stat3  as LISTBOX VISIBLE LENGTH 8 MODIF ID g3.
SELECTION-SCREEN POSITION 60.
PARAMETERS : P_C3 AS CHECKBOX MODIF ID G3 USER-COMMAND C1.
SELECTION-SCREEN COMMENT 65(5) TEXT-012 FOR FIELD P_C3 MODIF ID G3.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(23) TEXT-005 FOR FIELD P_NPTR4 MODIF ID G4.
PARAMETERS: P_NPTR4 TYPE T8JO-PARTN  MODIF ID G4 MATCHCODE OBJECT DEBI,
            P_SPLT4 TYPE I MODIF ID G4.
PARAMETERS : p_stat4  as LISTBOX VISIBLE LENGTH 8 MODIF ID g4.
SELECTION-SCREEN POSITION 60.
PARAMETERS : P_C4 AS CHECKBOX MODIF ID G4 USER-COMMAND C1.
SELECTION-SCREEN COMMENT 65(5) TEXT-012 FOR FIELD P_C4 MODIF ID G4.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(23) TEXT-006 FOR FIELD P_NPTR5 MODIF ID G5.
PARAMETERS: P_NPTR5 TYPE T8JO-PARTN MODIF ID G5 MATCHCODE OBJECT DEBI,
            P_SPLT5 TYPE I MODIF ID G5.
PARAMETERS : p_stat5  as LISTBOX VISIBLE LENGTH 8 MODIF ID g5.
SELECTION-SCREEN POSITION 60.
PARAMETERS : P_C5 AS CHECKBOX MODIF ID G5 USER-COMMAND C1.
SELECTION-SCREEN COMMENT 65(5) TEXT-012 FOR FIELD P_C5 MODIF ID G5.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(23) TEXT-007 FOR FIELD P_NPTR6 MODIF ID G6.
PARAMETERS: P_NPTR6 TYPE T8JO-PARTN MODIF ID G6 MATCHCODE OBJECT DEBI,
            P_SPLT6 TYPE I MODIF ID G6.
PARAMETERS : p_stat6  as LISTBOX VISIBLE LENGTH 8 MODIF ID g6.
SELECTION-SCREEN POSITION 60.
PARAMETERS : P_C6 AS CHECKBOX MODIF ID G6 USER-COMMAND C1.
SELECTION-SCREEN COMMENT 65(5) TEXT-012 FOR FIELD P_C6 MODIF ID G6.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(23) TEXT-008 FOR FIELD P_NPTR7 MODIF ID G7.
PARAMETERS: P_NPTR7 TYPE T8JO-PARTN MODIF ID G7 MATCHCODE OBJECT DEBI,
            P_SPLT7 TYPE I MODIF ID G7.
PARAMETERS : p_stat7  as LISTBOX VISIBLE LENGTH 8 MODIF ID g7.
SELECTION-SCREEN POSITION 60.
PARAMETERS : P_C7 AS CHECKBOX MODIF ID G7 USER-COMMAND C1.
SELECTION-SCREEN COMMENT 65(5) TEXT-012 FOR FIELD P_C7 MODIF ID G7.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(23) TEXT-009 FOR FIELD P_NPTR8 MODIF ID G8.
PARAMETERS: P_NPTR8 TYPE T8JO-PARTN MODIF ID G8 MATCHCODE OBJECT DEBI,
            P_SPLT8 TYPE I MODIF ID G8.
PARAMETERS : p_stat8  as LISTBOX VISIBLE LENGTH 8 MODIF ID g8.
SELECTION-SCREEN POSITION 60.
PARAMETERS : P_C8 AS CHECKBOX MODIF ID G8 USER-COMMAND C1.
SELECTION-SCREEN COMMENT 65(5) TEXT-012 FOR FIELD P_C8 MODIF ID G8.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(23) TEXT-010 FOR FIELD P_NPTR9 MODIF ID G9.
PARAMETERS: P_NPTR9 TYPE T8JO-PARTN MODIF ID G9 MATCHCODE OBJECT DEBI,
            P_SPLT9 TYPE I MODIF ID G9.
PARAMETERS : p_stat9  as LISTBOX VISIBLE LENGTH 8 MODIF ID g9.
SELECTION-SCREEN POSITION 60.
PARAMETERS : P_C9 AS CHECKBOX MODIF ID G9 USER-COMMAND C1.
SELECTION-SCREEN COMMENT 65(5) TEXT-012 FOR FIELD P_C9 MODIF ID G9.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(23) TEXT-011 FOR FIELD P_NPTR10 MODIF ID G10.
PARAMETERS: P_NPTR10 TYPE T8JO-PARTN MODIF ID G10 MATCHCODE OBJECT DEBI,
            P_SPLT10 TYPE I MODIF ID G10.
PARAMETERS : p_stat10  as LISTBOX VISIBLE LENGTH 8 MODIF ID g10.
SELECTION-SCREEN END OF LINE.

PARAMETERS : P_EDATE  TYPE SY-DATUM     OBLIGATORY,
             P_EGDESC TYPE T8JFT-EGTXT  OBLIGATORY.
SELECT-OPTIONS :  S_VNAME FOR G_VNAME ,
                  S_ETYPE FOR G_ETYPE NO INTERVALS.
SELECTION-SCREEN: END OF BLOCK B1.
